import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/src/components/Header";
import Link from "next/link";
import { buttonVariants } from "@/src/components/ui/button";
import { Separator } from "@/src/components/ui/separator"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ART APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased h-full px-16 py-6 bg-slate-400`}
      >
        <Header>
          <nav className="flex flex-row py-4 gap-4 items-center color">
              <Link className="flex-1  text-white" href="./">Grammatico Madeline</Link>
              <Link 
                  href="/"
                  className={buttonVariants({size:"lg", variant:"outline"})} 
              >
                  Accueil
              </Link>
              <Link 
                  href="/admin"
                  className={buttonVariants({size:"lg", variant:"outline"})} 
              >
                  Admin
              </Link>
          </nav>
        </Header>
        <Separator/>
        <div className="flex flex-col gap-4 py-4">
          {children}
        </div>
      </body>
    </html>
  );
}
